version: '3'
services:
  web:
    build:
      context: . # this is where we want docker build
      dockerfile: Dockerfile.dev # this specify the name of docker file
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: . # this is where we want docker build
      dockerfile: Dockerfile.dev # this specify the name of docker file
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]